### ISSUE TITLE
Driver.getDevice(deviceData) results in non-catch-able error for unknown device

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#128]
**What is your Homey version (Settings → System)?**

1.5.5

**What did you try to achieve?**
from driver.j driver class to try to load a device, where it is unknown if the device is paired or even existing.

*Please include detailed steps how we can reproduce the issue*
```
try {
	let deviceData = { id: circleState.mac};
	let device = this.getDevice(deviceData);
	this.log(device);
} catch (error) {
	this.log('nu such device');
}
```

**What was the result?**
```
Error: invalid_device
    at Pw2pyDriver.getDevice (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:4538)
    at Pw2pyDriver.handleNewCircleState (/drivers/circle/driver.js:126:21)
    at MqttClient.mqttClient.on.on (/drivers/circle/driver.js:82:13)
    at emitThree (events.js:136:13)
    at MqttClient.emit (events.js:217:7)
    at MqttClient._handlePublish (/node_modules/mqtt/lib/client.js:886:12)
    at MqttClient._handlePacket (/node_modules/mqtt/lib/client.js:301:12)
    at process (/node_modules/mqtt/lib/client.js:257:12)
    at Writable.writable._write (/node_modules/mqtt/lib/client.js:267:5)
    at doWrite (/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:406:64)
```

...

**What did you expect as result?**
That the error can be caught
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
It looks like the getDevice function returns the Error instead of throwing it. You can use `if(device instanceof Error) {}` to check for this. We'll have to discuss internally about wether or not this is expected behaviour and if it is possible to change it without breaking existing apps that might rely on this already.

**Comment by gruijter** [comment]
ah, thx. Actually I would expect it to simply return undefined when it cannot return a valid device.

I will humbly wait for the verdict of the wise Athom :)

**Comment by gruijter** [comment]
Just for info. I used below to check if the returned value is a valid device or not:
``` 
const device = this.getDevice({ id: circleState.mac });
if (device instanceof Homey.Device) {
```

**Comment by WeeJeWel** [comment]
Yep, that's the right way!
